### ISSUE TITLE
Log information on the process when a function is triggered

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/vitadao-cli#14]
Log information on the process when a function is triggered such as: Verbose mode for all transactions in the background:

- Transaction IDs of all transactions (also between the contracts)
- Show outgoing and receiving addresses (from and to) for all transactions
- Estimated transaction time coo

**Comment by mrsmkl** [comment]
Which API should I use for estimating tx time?

**Comment by aaitor** [comment]
Maybe this one:
https://api.etherscan.io/apis

```
Gas Tracker APIs
Get Estimation of Confirmation Time
/api?module=gastracker&action=gasestimate&gasprice=2000000000&apikey=YourApiKeyToken

(Result returned in seconds, gasprice value in Wei)
```
